### ISSUE TITLE
Spawning in Void

### ISSUE THREAD

**Issue by Aequipondium** [Pokechu22/WorldDownloader#143]
After i close minecraft and start it again, the world i downloaded spawns me in the void with the build nowhere to be found, this is very irritating

**Comment by Pokechu22** [comment]
Can you post the log file from the download (.minecraft/logs/latest.log, making sure to use the .minecraft folder for the game install you're using when downloading)?

**Comment by Aequipondium** [comment]
I'm using it together with the Conquest Reforged launcher, so it and liteloader is installed in that folder instead of .minecraft

**Comment by Aequipondium** [comment]
A list of the things that come with the modpack outside of the 6000 extra blocks (Which are copied btw so that's all fine and good): Optifine, Worldedit, FastAsyncWorldEdit, WorldEditCUI, Betterfoliage, BetterFPS, Serverredirect, Foamfix, FullscreenWindowed, Journeymap and QuickHotbar. Also the log in the game folder.
[2019-09-30-2.log.gz](https://github.com/Pokechu22/WorldDownloader/files/3671639/2019-09-30-2.log.gz)

**Comment by Pokechu22** [comment]
I'm a bit confused by what you mean by "Which are copied btw so that's all fine and good".  Did the world correctly save, or did none of it save?  Or did it load correctly the first time, but then the second time you loaded the downloaded world it was missing?  Or is it only a single dimension that has these issues, and other dimensions are fine, and that's how you know the blocks aren't an issue?

**Comment by Aequipondium** [comment]
It saves everything, even the blocks that are introduced with the mod, as for dimensions, it's only the overworld.

**Comment by Pokechu22** [comment]
Hm.  Possibly there's some kind of mismatch between dimensions on the server and the list of dimensions that forge defaults to or something?  In the world folder what folders starting with `DIM` exist, and does the `region` folder exist?  Is it the same list as the backed-up copy of the world?

**Comment by Aequipondium** [comment]
DIM1, DIM-1 and DIM142, and yes there is a region folder. It is the same as the backups.

**Comment by Aequipondium** [comment]
Also, it's 1.12.2

**Comment by Pokechu22** [comment]
Hm.  Looking in the log file, I see the following (lines 7192 through 7226):

```
[00:10:45] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[00:10:45] [Server thread/INFO] [LiteLoader]: Baking listener list for IEventState with 1 listeners
[00:10:45] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[00:10:45] [Server thread/ERROR] [FML]: Cannot Hotload Dim: 142
java.lang.IllegalArgumentException: Could not get provider type for dimension 142, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:149) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:236) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:830) [MinecraftServer.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:117) [pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:10:45] [Server thread/ERROR] [FML]: Cannot Hotload Dim: 142
java.lang.IllegalArgumentException: Could not get provider type for dimension 142, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:149) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:236) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:830) [MinecraftServer.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:119) [pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

My guess is that there's some kind of dimension ID metadata that isn't being saved by WDL so whatever dimension 142 is supposed to be is instead getting some different ID, but I'm not sure if that's the case.  There might also be some kind of mod configuration to specify the dimension IDs used (but it seems like that would happen automatically...).  Apparently the list of used dimension IDs is saved in `level.dat`, so can you upload it? (preferably, the one from the backed-up copy of the world, in case loading the world and saving it replaced the contents with something else)

**Comment by Aequipondium** [comment]
Here are the level.dat files (There was one called old and i thought, just to be sure i'll add it too.)

[Level files.zip](https://github.com/Pokechu22/WorldDownloader/files/3693244/Level.files.zip)

**Comment by Pokechu22** [comment]
Hm, that's kinda odd.  There are 2 `DimensionData` tags, one of which is empty and the other contains `3 0 0 0 16384`.  Neither of those values seems right, but I don't know how forge handles dimensions.

Can you create a new world singleplayer world with the modpack and upload its level.dat?  That way I can see what's missing, hopefully.

**Comment by Aequipondium** [comment]
[New World.zip](https://github.com/Pokechu22/WorldDownloader/files/3720982/New.World.zip)

**Comment by sopheset111** [comment]
Re: The issue request I made then closed
In the level.dat where it has the generator options, is the biome listed as Minecraft:the_void?

**Comment by Aequipondium** [comment]
I've temporarily fixed it by copying a lot of segments with world edit, then saving it as a schematic and pasting it in another world. But this takes quite some time.

**Comment by Pokechu22** [comment]
It probably would be possible to just copy the .mca files from one dimension into another dimension, but I'm not sure exactly (there might be data within the chunk that makes that not work; I don't remember completely).  If that works it'd be a lot faster, though, since you can just copy all of them.

**Comment by Aequipondium** [comment]
I'll give it a try tomorrow and let you know what happens, gonna sleep now though.

**Comment by Aequipondium** [comment]
I recently noticed that the worlds i download only have 4 mca files in the region folder, while others have more. (Also sorry for the late reply)

**Comment by Aequipondium** [comment]
This is a damn resilient bug

**Comment by Aequipondium** [comment]
Even worse now, just instantly spawns me into the void

**Comment by Pokechu22** [comment]
That's really odd.  There's supposed to be a failsafe to keep that from happening where you'll spawn in the flying state, but I don't remember how it works (does it check if you've got ground under you?  Not sure if that'd even work for this issue...  and also, I think it must require creative mode, but I'm not sure how that part works either; if it does require creative mode you should be able to override the gamemode to creative in player overrides.)

I also meant to reply to the MCA part you posted a while back, but it slipped my mind; the number of MCA files you get depends on how much space you explore, but also it's one MCA file per 32x32 chunk area so if you restrict yourself to the area from -1024 to +1024 on x and z you'll only get 4 MCA files but walking in a straight line will give much more.

**Comment by Aequipondium** [comment]
It keeps me in creative mode so that's not it, Optifine isn't the issue either as it persists without it, let's see if i stand on the ground but i doubt that will work, also where should i copy the mca files into then?

**Comment by Aequipondium** [comment]
Nope, standing on the ground doesn't improve anything

**Comment by Pokechu22** [comment]
Regarding copying the MCA files: you can try copying the ones that are in an unusual dimension (`DIM###/region`) into those for the overworld (i.e. just `region`), which will overwrite them but will serve as a test case at least.

I checked, and the way the creative flight override works is this:

https://github.com/Pokechu22/WorldDownloader/blob/b1b279f948beec2d7dac7524eea8f584a866d8eb/share/src/main/java/wdl/WDL.java#L1155-L1159

Overriding the gamemode only sets the `Gamemode` field in level.dat, so perhaps it doesn't have the ability enabled (it would be enabled on load, I think, but perhaps it's not enabled yet during saving; the way abilities work is somewhat weird).  I'll need to test that...

**Comment by Aequipondium** [comment]
Gamemode doesn't do anything, dropping the mca files in the region folder doesn't seem to work either, do you see the map immediatly or is it somewhere in the world?

**Comment by Pokechu22** [comment]
It will be at the same coordinates in the new dimension as they were at in the old dimension (you don't need to account for e.g. the nether portal shift).  You might need to make sure you're in the overworld.

I can't remember if I already asked this, but are new chunks and a new dimension generated when you first load the world?

**Comment by Aequipondium** [comment]
When i first downloaded a world generated the world properly, now that doesn't even happen anymore and i just spawn into the void directly. As for chunks they are downloaded everytime properly, no warnings no errors. No chunks happen in the singleplayer world though since it's just void

**Comment by Aequipondium** [comment]
I dunno what to do

**Comment by Tsoccerguy3** [comment]
This is a bungee-cord issue . try this . before you log off press F3 and take a screenshot. Then log onto the map in single player , press F3 and take a screenshot and post the 2 images here

**Comment by Aequipondium** [comment]
Will do

**Comment by Aequipondium** [comment]
![2019-12-16_22 28 26](https://user-images.githubusercontent.com/55962315/70944517-82f9ba00-2053-11ea-9a6d-a3c18546ec6c.png)
![2019-12-16_22 28 56](https://user-images.githubusercontent.com/55962315/70944518-82f9ba00-2053-11ea-820a-4a09c6476357.png)
Sorry it took a while

**Comment by Aequipondium** [comment]
It's still a problem ;-;

**Comment by Aequipondium** [comment]
Sigh..

**Comment by Aequipondium** [comment]
Any help is still appreciated

**Comment by Pokechu22** [comment]
Hi.  Sorry for taking a while to reply; I've been busy.  After rereading everything, I have an idea for how to test further: forcing everything to save as if it was in dimension 0 (the overworld).  I can add something like that in the next version (which should be soon, since I should release something for 1.15.2 soon).  That would only be for test purposes and wouldn't actually fix the underlying problem, but it'd help understand what's happening.

One other thing to try (which I thought I asked before, but it looks like I didn't): when you start downloading, the multiworld select screen should show up.  What dimensions are listed there, for each world?

**Comment by Aequipondium** [comment]
Nether (#-1)
The End (#1)
#228
Overworld (#0)

**Comment by Pokechu22** [comment]
Try renaming the world's `DIM228` folder to `DIM142`.  Not sure if that'll solve it, but it might do something.

**Comment by Aequipondium** [comment]
Let's find out shall we

**Comment by Aequipondium** [comment]
Nope, didn't work either

**Comment by Pokechu22** [comment]
I've added an option to force the dimension to the overworld in the next version (should be out in an hour or so).  To enable it, you'll need to edit the `WorldDownoader.ini` file for the server (since you have multiworld enabled, you want the main one, not the one for any individual world; it'll have "These settings are shared across an entire server" at the top).  Add the line `ForceDimensionToOverworld=true` to it (and save the file), and then connect to the server.  You'll want to use a new multiworld world for each dimension you save.

I don't know if this will actually solve the issue, but it's an interesting test at least.

**Comment by Aequipondium** [comment]
Where is the file for the server located? Its not mine, I just want to safe a plot of mine

**Comment by Pokechu22** [comment]
Oops, I probably should have been clearer.  WDL in general 3 configuration files: one that's used for all servers (located in `.minecraft/WorldDownloader.txt`), one that's used for all worlds on a server (located in <code>.minecraft/saves/<var>ServerName</var>/WorldDownloader.txt</code>), and one that's used for an individual world (located in <code>.minecraft/saves/<var>ServerName</var> - <var>WorldName</var>/WorldDownloader.txt</code>).  All of those files are located in your minecraft install, not on the server itself.  The one you need to edit is <code>.minecraft/saves/<var>ServerName</var>/WorldDownloader.txt</code>.

**Comment by Aequipondium** [comment]
You know what? You're a fucking genius. That worked!

**Comment by BeastSoup666** [comment]
Hey I just had the same problem with spawnig in the void after trying to download my plot of a server using ConquestReforged 1.12.2 mod... What do I need to edit in .minecraft/saves/ServerName/WorldDownloader.txt to change the void back to the plot I wanted?
