### ISSUE TITLE
bug when afk-ing on 1.12.2

### ISSUE THREAD

**Issue by traysoncombs** [Pokechu22/WorldDownloader#156]
So I have been using baritone ([baritone's github](https://github.com/cabaletta/baritone)) with the baseedit version of this on 1.12.2 and about every ten or so minutes if minecraft doesn't get any user input it will just leave the server, not because of some anti-afk plugin on the server as baritone is making me move. This is odd because it doesn't full on crash just freezes for a second and sends me to the title screen. Here is a portion of the log file, where I think the error is occurring:

[22:31:17] [main/INFO]: [CHAT] [WorldDL] Download stopped.
[22:31:17] [main/INFO]: [CHAT] [WorldDL] Save started.
[22:31:17] [WDL Save Thread/INFO]: Failed to call FML writeVersionData
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.FMLCommonHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241]
	at wdl.WDL.addForgeDataToWorldInfo(WDL.java:1304) ~[WDL.class:?]
	at wdl.WDL.applyOverridesToWorldInfo(WDL.java:1297) ~[WDL.class:?]
	at wdl.WDL.saveWorldInfo(WDL.java:829) ~[WDL.class:?]
	at wdl.WDL.saveEverything(WDL.java:643) ~[WDL.class:?]
	at wdl.WDL.lambda$startSaveThread$4(WDL.java:507) ~[WDL.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
[22:31:17] [WDL Save Thread/INFO]: Failed to call FML handleWorldDataSave
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.FMLCommonHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241]
	at wdl.WDL.addForgeDataToWorldInfo(WDL.java:1315) ~[WDL.class:?]
	at wdl.WDL.applyOverridesToWorldInfo(WDL.java:1297) ~[WDL.class:?]
	at wdl.WDL.saveWorldInfo(WDL.java:829) ~[WDL.class:?]
	at wdl.WDL.saveEverything(WDL.java:643) ~[WDL.class:?]
	at wdl.WDL.lambda$startSaveThread$4(WDL.java:507) ~[WDL.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[22:31:17] [WDL Save Thread/INFO]: [WorldDL] Using old BE from saved file: minecraft:chest at Pos[x=2521, y=33, z=780]
[22:31:19] [pool-5-thread-13/INFO]: [STDOUT]: Started saving the world in a new thread
[22:31:19] [pool-5-thread-14/INFO]: [STDOUT]: Started saving saved containers in a new thread
[22:31:19] [pool-5-thread-13/INFO]: [STDOUT]: Saving region 4,0 to disk C:\Users\trays\Downloads\mmc-stable-win32\MultiMC\instances\1.12.2-pp\.minecraft\baritone\us.9b9t.com\DIM0\cache
[22:31:19] [ForkJoinPool.commonPool-worker-15/INFO]: [STDOUT]: Saving region 4,1 to disk C:\Users\trays\Downloads\mmc-stable-win32\MultiMC\instances\1.12.2-pp\.minecraft\baritone\us.9b9t.com\DIM0\cache
[22:31:19] [ForkJoinPool.commonPool-worker-13/INFO]: [STDOUT]: Saving region 5,1 to disk C:\Users\trays\Downloads\mmc-stable-win32\MultiMC\instances\1.12.2-pp\.minecraft\baritone\us.9b9t.com\DIM0\cache
[22:31:19] [ForkJoinPool.commonPool-worker-6/INFO]: [STDOUT]: Saving region 4,2 to disk C:\Users\trays\Downloads\mmc-stable-win32\MultiMC\instances\1.12.2-pp\.minecraft\baritone\us.9b9t.com\DIM0\cache
[22:31:19] [main/INFO]: [CHAT] [WorldDL] Saving player data...
[22:31:19] [main/INFO]: [CHAT] [WorldDL] Player data saved.
[22:31:19] [main/INFO]: [CHAT] [WorldDL] Saving world metadata...
[22:31:19] [main/INFO]: [CHAT] [WorldDL] World metadata saved.
[22:31:19] [main/INFO]: [CHAT] [WorldDL] Saving map data...
[22:31:19] [main/INFO]: [CHAT] [WorldDL] Map data saved.
[22:31:19] [main/INFO]: [CHAT] [WorldDL] Saving chunks...
[22:31:19] [main/INFO]: [CHAT] [WorldDL] Chunk data saved.
[22:31:19] [main/INFO]: [CHAT] [WorldDL] Waiting for ThreadedFileIOBase to finish...
[22:31:19] [main/INFO]: [CHAT] [WorldDL] Save complete. Your single player file is ready to play!
[22:31:19] [main/ERROR]: Setting skin to impaste
[22:31:19] [ForkJoinPool.commonPool-worker-13/INFO]: [STDOUT]: Saved region successfully
[22:31:19] [ForkJoinPool.commonPool-worker-6/INFO]: [STDOUT]: Saved region successfully
[22:31:19] [pool-5-thread-13/INFO]: [STDOUT]: Saved region successfully
[22:31:20] [ForkJoinPool.commonPool-worker-15/INFO]: [STDOUT]: Saved region successfully
[22:31:20] [pool-5-thread-13/INFO]: [STDOUT]: World save took 288ms

**Comment by Pokechu22** [comment]
The two error messages there are normal if you don't have forge installed.  Sounds to me like you're just getting disconnected for some reason, and WDL is stopping download and saving since you did get disconnected.  The reason for the disconnect doesn't seem to be visible in the log though.
