### ISSUE TITLE
MultiMC Installation on Mac

### ISSUE THREAD

**Issue by pinfatt** [Pokechu22/WorldDownloader#171]
Hi,

I've followed the instructions step by step to install this via MultiMC on my Mac, and it isn't working at all. I've tried the other methods on the page but it never gives me an option to download the world in my Menus.

Any ideas?

Cheers

**Comment by Pokechu22** [comment]
To verify, you used the "add to minecraft.jar" button to install the mod, and also are using the version of the mod that matches your Minecraft version, right?

If so, can you force a game crash by holding F3+C for 10 seconds while ingame, and then attach that crash report here?

**Comment by pinfatt** [comment]
Yeah added to the Minecraft.jar and used the same version. Wasn't exactly sure which part the crash report is so pasted the whole thing:

MultiMC version: 0.6.11-1370


Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/1.15.2_WDL/.minecraft


Java path is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java


Java is version 1.8.0_251, using 64-bit architecture.


Main Class:
  net.minecraft.client.main.Main

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/1.15.2_WDL/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/instances/1.15.2_WDL/.minecraft/bin/minecraft.jar

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Jar Mods:
  mod-worlddownloader-baseedit-4 3 (6ca25121-9f30-420e-ba70-213b985fabb1.jar)

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/1.15.2_WDL/.minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.15 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.15.2_WDL", -XstartOnFirstThread, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 1552


Using onesix launcher.

[22:47:07] [Render thread/INFO]: Setting user: pattissonfg
[22:47:12] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[22:47:15] [Render thread/INFO]: Reloading ResourceManager: Default
[22:47:29] [Render thread/INFO]: OpenAL initialized.
[22:47:29] [Render thread/INFO]: Sound engine started
[22:47:29] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[22:47:29] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[22:47:29] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:47:29] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:47:29] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22:47:29] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22:47:29] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:47:29] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[22:47:29] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22:47:29] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:47:34] [Render thread/WARN]: Unable to start LAN server detection: Can't assign requested address
[22:47:37] [Render thread/INFO]: Connecting to www.mumausserver.com, 25565
[22:47:39] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[22:47:39] [Render thread/INFO]: [CHAT] ➡ pattissonfg
[22:47:40] [Render thread/INFO]: Loaded 44 advancements
[22:47:43] [Render thread/INFO]: [CHAT] There are 1 out of maximum 120 players online.
[22:47:43] [Render thread/INFO]: [CHAT] c-prisoner: pattissonfg
[22:47:54] [Render thread/INFO]: [CHAT] » Journal: Want to become a prison guard? Submit an application! Visit https://mumausserver.com/forum for more info
[22:48:01] [Render thread/INFO]: [CHAT] [Debug]: Copied location to clipboard
[22:48:02] [Render thread/INFO]: [CHAT] [Debug]: F3 + C is held down. This will crash the game unless released.
[22:48:03] [Render thread/INFO]: [CHAT] [Debug]: Crashing in 8...
[22:48:04] [Render thread/INFO]: [CHAT] [Debug]: Crashing in 7...
[22:48:05] [Render thread/INFO]: [CHAT] [Debug]: Crashing in 6...
[22:48:06] [Render thread/INFO]: [CHAT] [Debug]: Crashing in 5...
[22:48:07] [Render thread/INFO]: [CHAT] [Debug]: Crashing in 4...
[22:48:08] [Render thread/INFO]: [CHAT] [Debug]: Crashing in 3...
[22:48:09] [Render thread/INFO]: [CHAT] [Debug]: Crashing in 2...
[22:48:10] [Render thread/INFO]: [CHAT] [Debug]: Crashing in 1...
[22:48:12] [Render thread/FATAL]: Reported exception thrown!
q: Manually triggered debug crash
	at dbl.b(SourceFile:454) ~[minecraft.jar:?]
	at dbn.p(SourceFile:1511) ~[minecraft.jar:?]
	at dbn.d(SourceFile:964) ~[minecraft.jar:?]
	at dbn.d(SourceFile:619) [minecraft.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.Throwable
	... 13 more
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 17/05/20 22:48
Description: Manually triggered debug crash

java.lang.Throwable
	at dbl.b(SourceFile:454)
	at dbn.p(SourceFile:1511)
	at dbn.d(SourceFile:964)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dbl.b(SourceFile:454)

-- Affected level --
Details:
	All players: 1 total; [dqb['pattissonfg'/90723, l='MpServer', x=49.05, y=68.00, z=84.70]]
	Chunk stats: Client Chunk Cache: 361, 225
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -5137292142607401144
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (42,68,85), Chunk: (at 10,4,5 in 2,5; contains blocks 32,0,80 to 47,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 111817 game time, 1330321636 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dno.a(SourceFile:450)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:634)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 443595256 bytes (423 MB) / 881852416 bytes (841 MB) up to 954728448 bytes (910 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) Iris(TM) Plus Graphics 640 GL version 2.1 INTEL-12.10.17, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
#@!@# Game crashed! Crash report saved to: #@!@# /Applications/MultiMC.app/Contents/MacOS/instances/1.15.2_WDL/.minecraft/crash-reports/crash-2020-05-17_22.48.12-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.

**Comment by pinfatt** [comment]
Just found this my bad

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 17/05/20 22:48
Description: Manually triggered debug crash

java.lang.Throwable
	at dbl.b(SourceFile:454)
	at dbn.p(SourceFile:1511)
	at dbn.d(SourceFile:964)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dbl.b(SourceFile:454)

-- Affected level --
Details:
	All players: 1 total; [dqb['pattissonfg'/90723, l='MpServer', x=49.05, y=68.00, z=84.70]]
	Chunk stats: Client Chunk Cache: 361, 225
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -5137292142607401144
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (42,68,85), Chunk: (at 10,4,5 in 2,5; contains blocks 32,0,80 to 47,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 111817 game time, 1330321636 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dno.a(SourceFile:450)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:634)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 443595256 bytes (423 MB) / 881852416 bytes (841 MB) up to 954728448 bytes (910 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) Iris(TM) Plus Graphics 640 GL version 2.1 INTEL-12.10.17, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz

**Comment by Pokechu22** [comment]
Hmm, in the earlier bit (the multimc log), I see this:

> Jar Mods:
> mod-worlddownloader-baseedit-4 3 (6ca25121-9f30-420e-ba70-213b985fabb1.jar)

That's a slightly weird file name; the normal file name is `mod-worlddownloader-baseedit-4.0.6.2-mc1.15.2.zip` (for [version 4.0.6.2](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.6.2)), which should show up as `mod-worlddownloader-baseedit-4.0.6.2-mc1.15.2`.  Perhaps it downloaded weirdly?  Other than that, everything looks fine.

**Comment by pinfatt** [comment]
Do you know if there's a way of fixing this?

**Comment by Pokechu22** [comment]
I don't fully understand why it's happening.  Try downloading the mod again, and then opening the zip file; there should be files named similarly to `ajq.class` and `h.class` in it (as well as a subfolder named `wdl` containing a bunch of other files, and some other things).  If there aren't, something's gone wrong...

**Comment by pinfatt** [comment]
Yeah those files are in the zip when I open it up

**Comment by Pokechu22** [comment]
I don't know why it's not working then.  It works for me on Windows; is there any way for you to test Windows?  If Windows also doesn't work for you, then something even weirder is happening.

**Comment by pinfatt** [comment]
Afraid not mate only got access to a Mac

**Comment by Pokechu22** [comment]
Can you try installing the mod on an earlier MC version (say, 1.12.2)?  You can check if it was installed successfully by the buttons appearing in the singleplayer pause menu.  (This is to see if something is going wrong with 1.15.2, or installing it in general.)

**Comment by pinfatt** [comment]
Didn't work with 1.12.2 either. It must be the installing in general

**Comment by Pokechu22** [comment]
You can try following the [instructions to install it as a launcher profile](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds#Installation).  It's a rather complicated process, though.

You should also be able to use MultiMC's replace minecraft.jar functionality if you manually patch the minecraft jar (steps 7 and 8 in the instructions).  I've never tried doing it that way myself, but it may be easier than using the full profile instructions since you don't need to mess with the version JSON.

**Comment by TechGeekUnited** [comment]
This is only relevant now but now you could try downloading curseforge (https://download.curseforge.com/) if you don't have it Navigate to https://www.curseforge.com/minecraft/mc-mods/wdl/files and Click on the "Install With CurseForge App" Button, and say "Yes I Have CurseForge"  and install it with curseforge BC That sets up and downloads everything for you
