### ISSUE TITLE
Test failure on compile of 1.09.0: MapDataHandlerTest.testDimension

### ISSUE THREAD

**Issue by Brycey92** [Pokechu22/WorldDownloader#177]
When running `gradlew build` on the entire repo, `MapDataHandlerTest.testDimension` fails with the following error for 1.09.0:

```
java.lang.IllegalAccessError: tried to access class net.minecraft.world.WorldProviderHell$1 from class net.minecraft.world.dimension.NetherDimension
	at net.minecraft.world.dimension.NetherDimension.createWorldBorder(SourceFile:65)
	at net.minecraft.world.World.<init>(SourceFile:152)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:56)
	at wdl.ExtWorldClient.<init>(ExtWorld_1_10.java:48)
	at wdl.TestWorld$ClientWorld.<init>(TestWorld.java:63)
	at wdl.TestWorld$ClientWorld.<init>(TestWorld.java:60)
	at wdl.TestWorld.makeClient(TestWorld.java:44)
	at wdl.MapDataHandlerTest.testDimension(MapDataHandlerTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.spongepowered.lwts.runner.DelegateRunner.run(DelegateRunner.java:130)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Pokechu22** [comment]
What Java version are you using to compile?  This might be a Java 9+ issue, or it might be something else (e.g. an issue with how I do renaming for multi-version compatibility).

**Comment by Brycey92** [comment]
Java 8, update 251 x64. Could this be a missing or broken access transformer?

**Comment by Pokechu22** [comment]
Looks more like a broken remap on my end.  Try changing these:

https://github.com/Pokechu22/WorldDownloader/blob/5b713b6ef3992eb1ce176c9a56c6c1fa4c4a7d35/srgs/1.13.srg#L12-L17

for this:

```
# https://github.com/ModCoderPack/MCPBot-Issues/issues/90
CL: net/minecraft/world/DimensionType net/minecraft/world/dimension/DimensionType
CL: net/minecraft/world/WorldProvider net/minecraft/world/dimension/Dimension
CL: net/minecraft/world/WorldProviderEnd net/minecraft/world/dimension/EndDimension
CL: net/minecraft/world/WorldProviderHell net/minecraft/world/dimension/NetherDimension
CL: net/minecraft/world/WorldProviderHell$1 net/minecraft/world/dimension/NetherDimension$1
CL: net/minecraft/world/WorldProviderSurface net/minecraft/world/dimension/OverworldDimension
```

The thing that confuses me is that I *haven't* run into this issue, even though the current remap seems pretty broken (`WorldProviderOverworld` was a typo in addition to the missing `$1`).

**Comment by Brycey92** [comment]
I changed that, but now I get a new set of errors:
https://gist.github.com/Brycey92/5a03be419704b83dbc518b632d719766

**Comment by Pokechu22** [comment]
The important error there is this:

```
C:\Users\Bryce\Desktop\Forge development\WorldDownloader\1.09.4\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1349: error: cannot access AddPlayerData
                for (SPacketPlayerListItem.AddPlayerData spacketplayerlistitem$addplayerdata : packetIn.getEntries()) {
                                          ^
  bad class file: C:\Users\Bryce\Desktop\Forge development\WorldDownloader\1.09.4\.gradle\minecraft\minecraftBin-1.9.4-PROJECT(1.09.4).jar(net/minecraft/network/play/server/SPacketPlayerListItem$AddPlayerData.class)
    bad RuntimeInvisibleParameterAnnotations attribute: AddPlayerData(GameProfile,int,GameType,ITextComponent)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

You'll need to run `setupDecompWorkspace` again; this is a rather complicated bug with ForgeGradle (well, mixed throughout a bunch of other things).  The `MethodsReturnNonnullByDefault` errors should hopefully go away after `setupDecompWorkspace` too.

**Comment by Brycey92** [comment]
It looks like those errors are solved, but now I get the following after a massive series of stack traces: https://gist.github.com/Brycey92/e52c32522a4c159db5c2694d26909ab0

Do you know where gradle logs to on disk, so I can grab errors and stack traces more easily?

**Comment by Pokechu22** [comment]
You can use <code>gradlew <var>task</var> &gt; file.txt 2&gt;&amp;1</code> to capture the log output, but I don't think gradle writes logs anywhere directly.

**Comment by Brycey92** [comment]
Damn. In that case, do you need me to rerun it like that to get the stack traces, or is the error enough to go on?

**Comment by Pokechu22** [comment]
It would be helpful if you could re-run it with `--info` and `--stacktrace`.  You should be able to try just `gradlew :1.14.4-forge:build --info --stacktrace > log.txt 2>&1` to only attempt 1.14.4-forge, though.

**Comment by Brycey92** [comment]
[log.txt](https://github.com/Pokechu22/WorldDownloader/files/4767882/log.txt)

**Comment by Pokechu22** [comment]
> org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'JavaExec'.
> Caused by: java.lang.IllegalStateException: ProjectScopeServices has been closed.

According to https://github.com/MinecraftForge/ForgeGradle/issues/642 this is caused by the gradle daemon; you should be able to fix it by adding the `--no-daemon` flag.

**Comment by Brycey92** [comment]
Awesome, it worked this time! We should probably add all this to build properties and/or instructions in the readme. I added a line to `gradle.properties` to disable the daemon, and another line to raise the memory limit to 3GB as Forge suggests for decompiling MC. I've included that and the updated `1.13.srg` file in a PR #178.

It may be possible to include `ForgeGradle-extensions` as a git module, and it may also be possible to run `gradlew install` on that via your `build.gradle` when a build is started for the first time in your main directory.

**Comment by Pokechu22** [comment]
Thanks for the PR!

> It may be possible to include `ForgeGradle-extensions` as a git module, and it may also be possible to run `gradlew install` on that via your `build.gradle` when a build is started for the first time in your main directory.

I think that's theoretically possible, but I don't think it's worth doing that, just due to the extra overhead that might occur for building each time (and git submodules requiring cloning in a special way).  I'm also not sure if gradle works well with buildscript dependencies that need to be compiled before it evaluates other buildscripts; to my understanding it evaluates all subprojects' buildscripts first and then builds them.  Even if it is possible, it probably would be better for me to just figure out how to use GitHub's packages system.

**Comment by Brycey92** [comment]
Hey, thanks for responding so consistently quickly and helping me solve all these problems!

I figured messing with submodules and the buildscript would be a hassle, so if you don't think it's worth the effort and overhead, there you go. :stuck_out_tongue:
