### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9d60f60dc, pid=12328, tid=11140

### ISSUE THREAD

**Issue by Aalhond** [Pokechu22/WorldDownloader#22]
Hi there!

Ever since the 1.9 update I've been getting erorrs when trying to launch WDL. I've tried all versions and all installation methods. The 1.8 liteloader version of your mod worked perfectly.

Kind regards,
Alex

```

MultiMC version: 0.4.11-751

Minecraft folder is:
instances/1.9_WDL/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 12328

Using onesix launcher.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/instances/1.9_WDL/natives

Traits:
  []

Libraries:
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.8.7/realms-1.8.7.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/instances/1.9_WDL/minecraft.jar

Jar Mods:
  WorldDownloader_1.9a-beta2 (fb5e98a4-10ac-4305-87fb-36d337e354ab.jar)

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/instances/1.9_WDL/minecraft, --assetsDir, C:/Users/Alex/Documents/Minecraft/mmc-stable-win32/MultiMC/assets, --assetIndex, 1.9, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userType, mojang, --versionType, custom]

Window size: 854 x 480

Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[17:45:59] [Client thread/INFO]: Setting user: <PROFILE NAME>
[17:45:59] [Client thread/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
[17:46:00] [Client thread/INFO]: LWJGL Version: 2.9.1
[17:46:00] [Client thread/INFO]: Reloading ResourceManager: Default
[17:46:01] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:46:01] [Thread-4/INFO]: Initializing LWJGL OpenAL
[17:46:01] [Thread-4/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:46:01] [Thread-4/INFO]: OpenAL initialized.
[17:46:01] [Sound Library Loader/INFO]: Sound engine started
[17:46:02] [Client thread/INFO]: Created: 1024x512 textures-atlas
[17:46:26] [Client thread/INFO]: Connecting to play.edawg878.com., 25565
java.io.FileNotFoundException: C:\Users\Alex\Documents\Minecraft\mmc-stable-win32\MultiMC\instances\1.9_WDL\minecraft\WorldDownloader.txt (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at wdl.WDL.<clinit>(WDL.java:340)
	at wdl.WDLHooks.onWorldClientDoPreChunk(WDLHooks.java:172)
	at bku.b(WorldClient.java:176)
	at bks.a(NetHandlerPlayClient.java:786)
	at gp.a(SourceFile:64)
	at gp.a(SourceFile:12)
	at fh$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at g.a(SourceFile:45)
	at bcf.av(SourceFile:954)
	at bcf.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[17:46:28] [Client thread/INFO]: [WorldDL] Sending plugin channel registration.
[17:46:28] [Client thread/INFO]: [WorldDL] onWorldLoad: different server!
[17:46:28] [Client thread/INFO]: [WorldDL] Server brand = Spigot.  Using spigot track distances.
[17:46:28] [Client thread/INFO]: [CHAT] -*- Welcome to EDawg878's Creative Server -*-
[17:46:28] [Client thread/INFO]: [CHAT] /global Enter global chat
[17:46:28] [Client thread/INFO]: [CHAT] /local Enter local plot chat
[17:46:28] [Client thread/INFO]: [CHAT] /gm <0/1/2> Change gamemodes
[17:46:28] [Client thread/INFO]: [CHAT] /item <item> [qty] Spawn items
[17:46:28] [Client thread/INFO]: [CHAT] /clear Clear inventory
[17:46:28] [Client thread/INFO]: [CHAT] /pickup Toggle item pickup
[17:46:28] [Client thread/INFO]: [CHAT] /drops Toggle item drops
[17:46:28] [Client thread/INFO]: [CHAT] /phome [player] [#] Teleport to a plot
[17:46:28] [Client thread/INFO]: [CHAT] /plot <add/remove> <player> Give or revoke plot access
[17:46:28] [Client thread/INFO]: [CHAT] /plot <ban/unban> <player> Plot ban management
[17:46:28] [Client thread/INFO]: [CHAT] /plot trust <player> Trust a player to your plot
[17:46:28] [Client thread/INFO]: [CHAT] /playertime reset Sync to world time (day/night cycle)
[17:46:28] [Client thread/INFO]: [CHAT] During your stay, please abide by the rules listed at /rules
[17:46:28] [Client thread/INFO]: [CHAT] For more information see /help
[17:46:28] [Client thread/INFO]: [CHAT] You have 6 messages! Type /mail read to view your mail.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9d60f60dc, pid=12328, tid=11140
#
# JRE version: Java(TM) SE Runtime Environment (8.0_73-b02) (build 1.8.0_73-b02)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.73-b02 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig75icd64.dll+0x5560dc]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Alex\Documents\Minecraft\mmc-stable-win32\MultiMC\instances\1.9_WDL\minecraft\hs_err_pid12328.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1.
Clipboard copy at: 02 May 2016 17:53:33 +0200

```

**Comment by Pokechu22** [comment]
I'm pretty sure that this is a vanilla graphics card issue, but I can't access the bugtracker right now to confirm.  Generally anything involving `EXCEPTION_ACCESS_VIOLATION` (not to be confused with `IllegalAccessException`) means that there's a bug on something at the JVM level: either the JVM itself or a graphics card driver.

**Comment by Pokechu22** [comment]
Ah, found the bug report: [MC-32606](https://bugs.mojang.com/browse/MC-32606).  Their recommendation is to ideally update graphics card drivers, but if that isn't possible:

 * Change the launch parameters so that 2 gigabytes of RAM are allocated instead of 1 gigabyte (it looks like MultiMC is defaulting to 1 GB; I think MultiMC gives a simple way to edit this value but I'm not completely sure).
 * Enable VSync and VBOs in video settings

You probably changed one or both of those settings in the vanilla launcher but didn't in MultiMC, causing the issue to surface when launching WDL.

Hopefully doing that fixes your crash; if not I'll look into this further.

**Comment by Aalhond** [comment]
Ah grand! Thank you very much. That should also fix the random grapic card crashes that I get in vanilla mc.

**Comment by Pokechu22** [comment]
Closing, as this is resolved now.
