### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by ChiyoOsaka** [Pokechu22/WorldDownloader#23]
I got this crash yesterday, figure it might be useful.

````
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 14/05/16 22:20
Description: WDL mod: exception in onWorldClientTick event

java.lang.ClassCastException: aqi cannot be cast to aqg
	at wdl.WDLEvents.onItemGuiClosed(WDLEvents.java:403)
	at wdl.WDLHooks.onWorldClientTick(WDLHooks.java:94)
	at bku.d(WorldClient.java:102)
	at bcf.t(SourceFile:1658)
	at bcf.av(SourceFile:962)
	at bcf.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:375)

-- World Downloader Mod --
Details:
	Info: ### CORE INFO

WDL version: 1.9a-beta2
Launched version: 1.9-WDL
Client brand: worlddownloader1.9a-beta2-coremod
File location: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.9-WDL\1.9-WDL.jar

### EXTENSIONS

1 loaded

#### Hologram

Name: Hologram
Version: 1.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.9-WDL\1.9-WDL.jar
Implemented interfaces (2)
0: wdl.api.ISpecialEntityHandler
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@49476842 (sun.misc.Launcher$AppClassLoader)
Annotations (0)

### STATE

minecraft: bcf@5f4b2008
worldClient: bku@3bd92313
networkManager: ek@78fd1fd2
thePlayer: bmt['MyUsername'/13726406, l='MpServer', x=-4240.18, y=70.00, z=7772.55]
windowContainer: abh@69a3a6bd
lastClickedBlock: cj{x=-4240, y=71, z=7769}
lastEntity: null
saveHandler: azc@6fee90e1
chunkLoader: ass@1d5df7b4
newTileEntities: {cj{x=-4293, y=70, z=7740}=apx@d4e6842, cj{x=-4258, y=70, z=7769}=apx@792ca118, cj{x=-4260, y=70, z=7773}=apx@62de5f44, cj{x=-4257, y=70, z=7769}=apx@104cf4fc, cj{x=-4291, y=70, z=7742}=apx@6ebe92cf, cj{x=-4259, y=70, z=7773}=apx@7286da61, cj{x=-4293, y=64, z=7739}=apx@62b28f0a, cj{x=-4281, y=70, z=7736}=apx@15ae7cb4, cj{x=-4250, y=70, z=7769}=apx@f1cac24, cj{x=-4293, y=60, z=7737}=apx@4b0d2a74, cj{x=-4251, y=70, z=7769}=apx@3d3136c0, cj{x=-4287, y=66, z=7740}=apx@5b9cb60e, cj{x=-4293, y=60, z=7739}=apx@310b4cd5, cj{x=-4306, y=64, z=7759}=apx@13778e0a, cj{x=-4292, y=60, z=7741}=aqg@27c42d92, cj{x=-4281, y=70, z=7740}=apx@1956d3a2, cj{x=-4283, y=70, z=7742}=apx@72d059b9, cj{x=-4243, y=70, z=7767}=apx@5df89e37, cj{x=-4239, y=73, z=7769}=apx@5bd690a7, cj{x=-4240, y=73, z=7769}=apx@74b293bc, cj{x=-4281, y=61, z=7736}=apx@4df0102, cj{x=-4282, y=59, z=7735}=aqg@1dcf3e88, cj{x=-4281, y=59, z=7737}=apx@7273d63e, cj{x=-4281, y=59, z=7739}=apx@123c84bf, cj{x=-4281, y=61, z=7740}=apx@6e9740eb, cj{x=-4293, y=70, z=7736}=apx@a4808cf, cj{x=-4263, y=73, z=7779}=apx@6666fd9e, cj{x=-4263, y=73, z=7777}=apx@10899491, cj{x=-4293, y=61, z=7736}=apx@44cd0e73, cj{x=-4293, y=59, z=7739}=apx@e097855, cj{x=-4293, y=61, z=7740}=apx@5fd2ee07, cj{x=-4287, y=69, z=7742}=apx@323c470, cj{x=-4287, y=59, z=7735}=apx@2fb1ecf1, cj{x=-4292, y=59, z=7741}=aqg@6abff282, cj{x=-4285, y=64, z=7742}=apx@22559b04, cj{x=-4240, y=72, z=7769}=apx@3f48cb7a, cj{x=-4241, y=72, z=7769}=apx@1f3e6e06, cj{x=-4281, y=60, z=7736}=apx@a00a481, cj{x=-4284, y=64, z=7742}=apx@483937e, cj{x=-4272, y=73, z=7771}=apx@7d699b8f, cj{x=-4239, y=72, z=7769}=aqi@11cb947a, cj{x=-4281, y=60, z=7740}=apx@1ee01e6e, cj{x=-4265, y=71, z=7774}=apx@6e066af, cj{x=-4264, y=73, z=7775}=apx@37e4301f, cj{x=-4293, y=64, z=7738}=apx@7ac10add, cj{x=-4293, y=60, z=7736}=apx@64cc6885, cj{x=-4293, y=60, z=7740}=apx@611cbfad, cj{x=-4243, y=70, z=7766}=apx@77ee0f59, cj{x=-4306, y=64, z=7760}=apx@58b749b, cj{x=-4283, y=59, z=7734}=aqg@284acef, cj{x=-4288, y=59, z=7742}=apx@6619ac5, cj{x=-4281, y=61, z=7737}=apx@1f2c997, cj{x=-4239, y=71, z=7769}=aqg@5f034a9e, cj{x=-4289, y=59, z=7742}=apx@78c76645, cj{x=-4240, y=71, z=7769}=aqi@727a7c2a, cj{x=-4286, y=59, z=7742}=apx@6553ad83, cj{x=-4281, y=61, z=7739}=apx@20c14c0d, cj{x=-4281, y=59, z=7736}=apx@63f7e31e, cj{x=-4285, y=59, z=7742}=apx@424d5866, cj{x=-4281, y=59, z=7740}=apx@3a8ada19, cj{x=-4278, y=64, z=7751}=apx@10814861, cj{x=-4263, y=73, z=7776}=apx@4cb2b67c, cj{x=-4259, y=71, z=7773}=apx@641449e4, cj{x=-4260, y=71, z=7773}=apx@8a21d6d, cj{x=-4287, y=69, z=7737}=apx@127a9e58, cj{x=-4288, y=69, z=7737}=apx@4b22cb3d, cj{x=-4293, y=61, z=7737}=apx@d3ff0d4, cj{x=-4285, y=69, z=7737}=apx@156ecd6b, cj{x=-4251, y=71, z=7769}=apx@532019c0, cj{x=-4290, y=59, z=7734}=apx@e065bba, cj{x=-4293, y=61, z=7739}=apx@7c4da3fe, cj{x=-4284, y=69, z=7737}=apx@1f2b3c89, cj{x=-4250, y=71, z=7769}=apx@4c16c8b5, cj{x=-4287, y=59, z=7734}=apx@70718106, cj{x=-4293, y=59, z=7740}=apx@61328ea5, cj{x=-4240, y=70, z=7769}=apx@27bb397e, cj{x=-4241, y=70, z=7769}=apx@5d920e5c, cj{x=-4281, y=60, z=7737}=apx@2117cd59, cj{x=-4281, y=60, z=7739}=apx@54a53878, cj{x=-4265, y=71, z=7769}=apx@2a2b8b5b, cj{x=-4266, y=71, z=7769}=apx@670690ac}
newEntities: {15278127=yd['item.item.reeds'/15278127, l='MpServer', x=-4280.53, y=49.00, z=7765.25], 15335916=yd['item.item.reeds'/15335916, l='MpServer', x=-4278.88, y=49.00, z=7767.91], 15264099=xs['entity.ItemFrame.name'/15264099, l='MpServer', x=-4287.03, y=66.50, z=7740.50], 15264100=xs['entity.ItemFrame.name'/15264100, l='MpServer', x=-4286.50, y=70.50, z=7741.97], 15264102=yd['item.item.reeds'/15264102, l='MpServer', x=-4279.13, y=48.00, z=7760.72], 15266104=we['Sheep'/15266104, l='MpServer', x=-4227.72, y=11.00, z=7816.78], 15266107=we['Sheep'/15266107, l='MpServer', x=-4230.97, y=11.00, z=7817.06], 15266108=we['Sheep'/15266108, l='MpServer', x=-4228.25, y=11.00, z=7817.44], 15266109=we['Sheep'/15266109, l='MpServer', x=-4234.56, y=11.00, z=7818.13], 15264190=yi['Creeper'/15264190, l='MpServer', x=-4266.50, y=37.00, z=7794.50], 15264191=yw['Skeleton'/15264191, l='MpServer', x=-4270.50, y=42.00, z=7800.50], 15266111=wd['Rabbit'/15266111, l='MpServer', x=-4230.47, y=11.00, z=7822.47], 15266098=yi['Creeper'/15266098, l='MpServer', x=-4224.50, y=26.00, z=7712.50], 15266099=yw['Skeleton'/15266099, l='MpServer', x=-4227.50, y=32.00, z=7713.50], 15266102=ze['Villager'/15266102, l='MpServer', x=-4236.91, y=11.00, z=7817.31], 15267208=yi['Creeper'/15267208, l='MpServer', x=-4217.50, y=29.00, z=7716.50], 15267209=yw['Skeleton'/15267209, l='MpServer', x=-4216.81, y=77.00, z=7752.25], 15273803=vu['Bat'/15273803, l='MpServer', x=-4265.19, y=35.94, z=7798.63], 15267210=vy['Cow'/15267210, l='MpServer', x=-4218.66, y=62.54, z=7765.81], 15264192=yi['Creeper'/15264192, l='MpServer', x=-4266.50, y=51.00, z=7799.50], 15266112=vy['Cow'/15266112, l='MpServer', x=-4238.78, y=11.00, z=7823.72], 15264193=za['Zombie'/15264193, l='MpServer', x=-4268.63, y=65.00, z=7796.28], 15267207=yi['Creeper'/15267207, l='MpServer', x=-4214.50, y=30.00, z=7711.50], 15304977=yd['item.item.reeds'/15304977, l='MpServer', x=-4279.88, y=48.00, z=7760.72], 15262165=za['Zombie'/15262165, l='MpServer', x=-4295.50, y=32.00, z=7790.50], 15264726=xs['entity.ItemFrame.name'/15264726, l='MpServer', x=-4246.97, y=71.50, z=7766.50]}
newMapDatas: {881=ayz@7864e410, 883=ayz@57f759c, 884=ayz@73f8573b, 885=ayz@20283a18, 886=ayz@7f330e69, 890=ayz@11e5786, 891=ayz@306e9911}
downloading: true
isMultiworld: true
propsFound: true
startOnChange: true
overrideLastModifiedCheck: false
saving: false
worldLoadingDeferred: false
worldName: Some town
baseFolderName: ServerNameHere
### CONNECTED SERVER

Name: ServerNameHere
IP: ServerIPHere

### PROPERTIES


#### BASE

Messages.enableAll: true
Messages.REMOVE_ENTITY: false
Messages.PLUGIN_CHANNEL_MESSAGE: false
Messages.INFO: true
Messages.ON_MAP_SAVED: false
LinkedWorlds: |World1|World2|World3|World4|World5|Some town
Messages.ON_GUI_CLOSED_INFO: true
Messages.ON_GUI_CLOSED_WARNING: true
Messages.LOAD_TILE_ENTITY: false
ServerName: NameHere
Messages.SAVING: true
Messages.ON_WORLD_LOAD: false
Messages.ON_CHUNK_NO_LONGER_NEEDED: false

#### WORLD

WorldName: Some town

#### DEFAULT

TutorialShown: true
UpdateETag: "fd859f3f951c362a089854b87be9fcf3"

Stacktrace:
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:375)
	at b.h(CrashReport.java:129)
	at b.<init>(CrashReport.java:47)
	at b.a(CrashReport.java:400)
	at wdl.WDL.crashed(WDL.java:1943)
	at wdl.WDLHooks.onWorldClientTick(WDLHooks.java:160)
	at bku.d(WorldClient.java:102)
	at bcf.t(SourceFile:1658)
	at bcf.av(SourceFile:962)
	at bcf.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 426606712 bytes (406 MB) / 1342201856 bytes (1280 MB) up to 2040135680 bytes (1945 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 4, tcache: 46, allocated: 13, tallocated: 95
````

**Comment by Pokechu22** [comment]
```
java.lang.ClassCastException: aqi cannot be cast to aqg
```

That means that it tried to convert a `TileEntityHopper` into a `TileEntityFurnace`.  Line 403 is part of the logic for furnace GUIs, and `windowContainer: abh@69a3a6bd` shows that the current container was a `ContainerFurnace`.

I have a guess as to why this happened (and it's a bug), but can you get a general screenshot of the area you were in?  Are there both hoppers and furnaces right next to each other?

**Comment by Pokechu22** [comment]
Making a guess - Is it likely that you were saving the contents of a furnace in a autosmelter like this one?

![A furnace-based autosmelter, with hoppers fed by/leading to chests on several sides of a furnace](https://cloud.githubusercontent.com/assets/8334194/15306558/766ec50e-1b80-11e6-8b6a-5ccf4b2cb721.png)

If so, I think I know what happened and this shouldn't be too hard to fix.

**Comment by ChiyoOsaka** [comment]
> Are there both hoppers and furnaces right next to each other?

Yes.

![Screenshot of smelters](https://i.imgur.com/SVcz01P.png)

Although, at the time, I wasn't looking at them or looking through the inventories. On the second attempt, I was able to save the contents successfully without any crashes.

**Comment by ChiyoOsaka** [comment]
I was where the red dot is, facing the way the stick is pointing. The autosmelting arrangement [above](https://github.com/Pokechu22/WorldDownloader/issues/23#issuecomment-219576446) is in the top right of this picture. (Inside the building of course)
![Where I was](https://i.imgur.com/qSD42aP.jpg)

**Comment by Pokechu22** [comment]
Were you saving the items in the furnaces at the time?

**Comment by ChiyoOsaka** [comment]
Nope.

**Comment by Pokechu22** [comment]
How long does it generally take for an inventory window to appear after you right-click a block?  Is it usually pretty fast, or does it a bit of time?

**Comment by ChiyoOsaka** [comment]
It's usually quick, sometimes depends on lag and the like.

**Comment by Pokechu22** [comment]
What I'm guessing is happening (I'm getting a similar crash when trying this) is that during the delay between right-clicking a block and the inventory appearing, the block you're looking at changes (either from mouse movement or player movement).  It's not possible to directly know what block a GUI corresponds with, so WDL uses the block that was being looked at when the GUI was opened.  In _most_ cases this is accurate, but (particularly with lag) it's posible to change the block being looked at by accident.

There are _supposed_ to be checks to make sure that the block being looked at matches the type of inventory being looked at, but it seems like those checks are missing on several inventories, including furnaces.  So it's possible for it to try and save a furnace in the tile entity used by a hopper, leading to this crash.  I'll fix those checks...

It only seems to happen when the drift happens between one type of container to another, so if look drifts from a chest to the ground, then the chest isn't saved but nothing will crash.

Easiest way to work around this bug is to make sure to keep the mouse steady while opening inventories.  That's (obviously) not too easy to remember to do, but it should be possible (that's probably why it worked the second time).

**Comment by Pokechu22** [comment]
I think I've fixed this code-wise.  I'm probably going to release a new beta version soon (which should also support 1.9.4), so that fix will be there too.

**Comment by Pokechu22** [comment]
Should be fixed in the latest release (for all minecraft versions).
