### ISSUE TITLE
It crashed

### ISSUE THREAD

**Issue by huzpsb** [Pokechu22/WorldDownloader#244]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  InputFix (if.jar)
  TransformerLoader (LiquidBounce-plus.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 22-2-11 下午7:30
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraftforge/fluids/FluidRegistry
	at net.minecraftforge.common.MinecraftForge.initialize(MinecraftForge.java:168)
	at net.minecraftforge.fml.common.FMLCommonHandler.beginLoading(FMLCommonHandler.java:146)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:205)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fluids.FluidRegistry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [liquidbounce.forge.mixins.json:performance.forge.FluidRegistryMixin_Optimization] from phase [DEFAULT] in config [liquidbounce.forge.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field bucketFluids was not located in the target class net.minecraftforge.fluids.FluidRegistry. Using refmap liquidbounce.mixins.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:563)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:263)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:358)

-- World Downloader Mod --
Details:
	Info: ### CORE INFO

WDL version: 1.8.9a-beta2
Launched version: HMCL 3.2.130
Client brand: fml,forge
File location: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)

### EXTENSIONS

2 loaded

#### Hologram

Id: Hologram
Version: 1.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.ISpecialEntityHandler
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@6093dd95 (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)

#### EntityRealigner

Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@6093dd95 (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)

### STATE

minecraft: net.minecraft.client.Minecraft@1e31e7e0
worldClient: null
networkManager: null
thePlayer: null
windowContainer: null
lastClickedBlock: null
lastEntity: null
saveHandler: null
chunkLoader: null
newTileEntities: {}
newEntities: {}
newMapDatas: {}
downloading: false
isMultiworld: false
propsFound: false
startOnChange: false
overrideLastModifiedCheck: false
saving: false
worldLoadingDeferred: false
worldName: WorldDownloaderERROR
baseFolderName: WorldDownloaderERROR
### CONNECTED SERVER

No data

#### BASE

empty

#### WORLD

empty

#### DEFAULT

empty

Stacktrace:
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:358)
	at net.minecraft.crash.CrashReport.handler$injectCrashEnv$zfa000(CrashReport.java:524)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:167)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:57)
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:333)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 165809272 bytes (158 MB) / 436207616 bytes (416 MB) up to 1056964608 bytes (1008 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx999m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
InputFix (if.jar)
  lain.mods.inputfix.InputFixTransformer
TransformerLoader (LiquidBounce-plus.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.patcher.tweaker.ClassTransformer
  net.ccbluex.liquidbounce.patcher.tweaker.other.ModClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8935' Renderer: 'Intel(R) UHD Graphics 630'
	Launched Version: HMCL 3.2.130
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 27.20.100.8935, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_I7
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8935
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Comment by Pokechu22** [comment]
This appears to be a conflict with whatever LiquidBounce-plus is, without any direct relevance to WDL.  Optifine has also been known to cause conflicts.

**Comment by huzpsb** [comment]
: (
