### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by bdomi2** [Pokechu22/WorldDownloader#30]
The server im trying to use this mod on is 1.7.10. When i try to connect to the server it crashes. I remove the mod and i can get on the server. Im trying to copy a part to use on a single player map.

**Comment by bdomi2** [comment]
using base edit beta 2 the others don't seem to work at all

**Comment by Pokechu22** [comment]
Can you post the crash report?

**Comment by bdomi2** [comment]
does not come up with anything just exits minecraft

**Comment by Pokechu22** [comment]
Hm, that's unusual (I don't know of any case where the game closes abnormally without a crash report).  Can you try going to the crash-reports folder (open the launcher, then select "edit profile", then "open game dir", then open the "crash-reports")?  It most likely (hopefully) generated a crash report there, even if the launcher didn't display it.

**Comment by bdomi2** [comment]
[crash-2016-06-28_16.05.16-client.txt](https://github.com/Pokechu22/WorldDownloader/files/336357/crash-2016-06-28_16.05.16-client.txt)

**Comment by bdomi2** [comment]
using magic launcher

**Comment by Pokechu22** [comment]
That's an odd crash report (it's happening _during the login process_, in the handler for the [encryption request packet](http://wiki.vg/index.php?title=Protocol&oldid=6003#Encryption_Request), due to a null UUID?).  I'm not entirely sure what would cause that, as it's pretty far beyond parts of the code WDL modifies.

There's a chance it's because of a combination of liteloader and the base edit, though I don't know entirely if that would cause issues.  There _is_ an 1.7.10 liteloader build by @uyjulian (though I haven't tested it much), which can currently be found on [page 14 of the forum post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2520465-1-10-1-9-4-1-8-9-world-downloader-mod-create?page=14) in the comments (it hasn't been added to the main post yet because there are issues with the update checker that make it hard to put in the version list - like #25 except harder to deal with).  It's possible that the liteloader version will work for you

**Comment by bdomi2** [comment]
[crash-2016-06-28_16.43.02-client.txt](https://github.com/Pokechu22/WorldDownloader/files/336398/crash-2016-06-28_16.43.02-client.txt)

**Comment by bdomi2** [comment]
tried it just got another crash report

**Comment by bdomi2** [comment]
sometimes it doesn't crash just says loading and nothing happens when connecting to server

**Comment by bdomi2** [comment]
[crash-2016-06-28_16.46.46-client.txt](https://github.com/Pokechu22/WorldDownloader/files/336406/crash-2016-06-28_16.46.46-client.txt)

**Comment by Pokechu22** [comment]
Hm, that's interesting (something is odd with that crash report).  I'll look at it more tomorrow, though.

**Comment by Pokechu22** [comment]
Seems be caused by a deliberate incompatibility in WesterosBlocks.  I'll talk with the relevant developers.  I don't have a workaround at this time.

**Comment by Stoakes** [comment]
Hi,

After mod loading, WesterosCraft mod tests if wdl.WDL is loaded in minecraft context. Therefore trying to install a distributed version of WorldDownloader can't work. A workaround would be to refactor code to change package or main class name.

**Comment by TheCrimsonKnight** [comment]
Hi guys!

I'm back and I've made progress on this issue. I took note of what Stoakes said about WesterosBlocks stopping Minecraft if you have WDL, and I did some stuff. I literally pretty much have no experience with this what so ever, but I went into WesterosBlocks' main class and found the code where it searches for WDL. I changed the name of what it looks for to "abc.WDL" instead of "wdl.WDL".  When I tested it, it let me on the server for a brief few seconds, and then it crashed. This time, I believe the crash is an entirely different problem and I don't know what it means because like I said I have no experience in this. 
If you could help out, we may have a chance of fixing this problem!

[crash-2016-07-07_21.46.32-client.txt](https://github.com/Pokechu22/WorldDownloader/files/353381/crash-2016-07-07_21.46.32-client.txt)

**Comment by uyjulian** [comment]
Did you delete the class "mods/octarinecore/Utils$sam$Supplier$ae950bb3" while you were editing WesterosBlocks' main class?

**Comment by Pokechu22** [comment]
The relevant part of that crash report seems to be this:

```
Caused by: java.lang.NoClassDefFoundError: java/util/function/Supplier
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 19 more
Caused by: java.lang.ClassNotFoundException: java.util.function.Supplier
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 23 more
```

... and this:

```
	Java Version: 1.7.0_80, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
```

Evidently one of the mods you're using (looks like Better Foliage) requires Java 8 (for `java.util.function.Supplier`) and you only have Java 7.  Update your Java version and make sure that Minecraft is launching with Java 8.

**Comment by TheCrimsonKnight** [comment]
Mon dieu, it works! Turns out we don't need those WesterosBlock authors to fix it! Thank you all c;

**Comment by Stoakes** [comment]
Nice.

How did you proceed to modify WesterosBlock ?

**Comment by TheCrimsonKnight** [comment]
I opened the mod file in 7zip and looked for "WesterosBlocks.class" which was located in the directory 

`\WesterosBlocks.jar\com\westeroscraft\westerosblocks\`

I opened that with Notepad++ and most of it was a lot of weird symbols because it was a class file, but the part where it looks for WDL.wdl wasn't messed up so I just changed it to something that doesn't exist in WDL.

**Comment by kwikwolf** [comment]
I am having the same issue. It looks like they never removed it. I've already went into the main class file and renamed the wdl.wdl file as abc.wdl, but for some reason when trying to connect to the server an error rejecting westerosblocks.
