### ISSUE TITLE
[LiteLoader] Client crashes when I click past MultiWold mode selection

### ISSUE THREAD

**Issue by louwers** [Pokechu22/WorldDownloader#34]
As soon as I click 'Done' (without enabling MultiWorld mode) my client crashes with the following error message.

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 8/8/16 12:09 PM
Description: Updating screen events

java.lang.RuntimeException: Failed to check session lock, aborting
	at azy.i(SourceFile:64)
	at azy.<init>(SourceFile:50)
	at azv.<init>(SourceFile:21)
	at azw.a(SourceFile:83)
	at wdl.WDL.startDownload(WDL.java:389)
	at wdl.WDL$2.onSelect(WDL.java:375)
	at wdl.gui.GuiWDLMultiworld.a(GuiWDLMultiworld.java:74)
	at bft.a(SourceFile:346)
	at wdl.gui.GuiWDLMultiworld.a(GuiWDLMultiworld.java:84)
	at bft.k(SourceFile:409)
	at bft.p(SourceFile:386)
	at bcx.t(SourceFile:1586)
	at bcx.av(SourceFile:968)
	at bcx.a(SourceFile:396)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at azy.i(SourceFile:64)
	at azy.<init>(SourceFile:50)
	at azv.<init>(SourceFile:21)
	at azw.a(SourceFile:83)
	at wdl.WDL.startDownload(WDL.java:389)
	at wdl.WDL$2.onSelect(WDL.java:375)
	at wdl.gui.GuiWDLMultiworld.a(GuiWDLMultiworld.java:74)
	at bft.a(SourceFile:346)
	at wdl.gui.GuiWDLMultiworld.a(GuiWDLMultiworld.java:84)
	at bft.k(SourceFile:409)
	at bft.p(SourceFile:386)

-- Affected screen --
Details:
	Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
	Level name: MpServer
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level time: 151412 game time, 378838206 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.10-SNAPSHOT:8627c86:unknown) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bln.a(SourceFile:364)
	at bcx.b(SourceFile:2535)
	at bcx.a(SourceFile:405)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10
	Operating System: Mac OS X (x86_64) version 10.11.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 114620760 bytes (109 MB) / 361467904 bytes (344 MB) up to 1060372480 bytes (1011 MB)
	Mod Pack: com.mumfrey.liteloader.crashreport.CallableLiteLoaderBrand@62edb254
	LiteLoader Mods: com.mumfrey.liteloader.crashreport.CallableLiteLoaderMods@6eb61a31
	LaunchWrapper: com.mumfrey.liteloader.crashreport.CallableLaunchWrapper@30dc14e4
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.10
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce 8600M GT OpenGL Engine GL version 2.1 NVIDIA-10.0.40 310.90.10.05b12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU T9300 @ 2.50GHz
```

I get this even with a fresh installation with no other mods installed. Tried it on multiple servers.

The weird thing is that it used to work... Hopefully you can determine the cause using the stacktrace.

**Comment by louwers** [comment]
I found the cause: my /saves folder was not writable (had it symlinked to an external HDD).

**Comment by Pokechu22** [comment]
> Failed to check session lock, aborting

That error happens when `session.lock` is unwritable – usually this means another session of the game is running in the same folder, but an unwritable HDD would do it too

**Comment by louwers** [comment]
Perhaps this exception can be caught and handled. 👍
