### ISSUE TITLE
Saving world

### ISSUE THREAD

**Issue by AlphaDelta9** [Pokechu22/WorldDownloader#40]
java.lang.NullPointerException: World Downloader Mod: Saving world
	at wdl.WDL.savePlayer(WDL.java:696)
	at wdl.WDL.saveEverything(WDL.java:624)
	at wdl.WDL$3.run(WDL.java:484)

**Comment by Pokechu22** [comment]
Minecraft version?  If this is 1.10 or 1.11, that line is `thePlayer.writeToNBT(playerNBT);` which shouldn't ever throw an NPE (`thePlayer` shouldn't ever be null, except _maybe_ on the first tick).

**Comment by AlphaDelta9** [comment]
1.10 and 1.11, sorry for late replay

**Comment by AlphaDelta9** [comment]
I want to tell you World Downloader isn't compatible with optifine (my provious ticket report bug about the text). I try to remove the optifine and the mod work fine. I hope you can fix it because old Developer make this mod compatible with optifine.

**Comment by AlphaDelta9** [comment]
This is the fatal error log(optifine first)
[crash-2016-12-22_15.36.49-client.txt](https://github.com/Pokechu22/WorldDownloader/files/668217/crash-2016-12-22_15.36.49-client.txt)

**Comment by Pokechu22** [comment]
Ah, yea, optifine would do that.

If you use the liteloader version instead of the base edit version it should work with opfitine (you can install liteloader with optifine the same way you'd install liteloader normally - no extra work needed).

I'll try to figure out why the base edit isn't compatible with optifine, but it's somewhat complicated to support multiple base edits together so I can't guarantee that I'll be able to get it to work.

**Comment by AlphaDelta9** [comment]
Thats Work Because Optifine Same Like Base Edit and World Downloader use Litemod. With This Method No One Problem I Get and Thanks For That Tips, Now I Use Liteloader+Forge+Optifine 👍
