### ISSUE TITLE
Error:Game ended with bad state (exit code 1)

### ISSUE THREAD

**Issue by L3ice** [Pokechu22/WorldDownloader#6]
Thats what I got in the Game Output when I wanted to start Minecraft:

```
Exception in thread "main" java.lang.SecurityException: SHA-256 digest error for bwy.class
	at sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:218)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:241)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:482)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main.main(SourceFile:40)
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

```
Thats what I got in the Launcher Log when I wanted to start Minecraft:

```
[18:02:06 INFO]: Minecraft Launcher 1.6.11 (through bootstrap 100) started on windows...
[18:02:06 INFO]: Current time is Jun 7, 2015 6:02:06 PM
[18:02:06 INFO]: System.getProperty('os.name') == 'Windows 7'
[18:02:06 INFO]: System.getProperty('os.version') == '6.1'
[18:02:06 INFO]: System.getProperty('os.arch') == 'amd64'
[18:02:06 INFO]: System.getProperty('java.version') == '1.8.0_25'
[18:02:06 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[18:02:06 INFO]: System.getProperty('sun.arch.data.model') == '64'
[18:02:06 INFO]: proxy == DIRECT
[18:02:07 INFO]: JFX is already initialized
[18:02:07 INFO]: Refreshing local version list...
[18:02:07 INFO]: Refreshing remote version list...
[18:02:08 INFO]: Refresh complete.
[18:02:08 INFO]: Loaded 5 profile(s); selected 'Default'
[18:02:08 INFO]: Refreshing auth...
[18:02:08 INFO]: Logging in with access token
[18:02:14 INFO]: Getting syncinfo for selected version
[18:02:14 INFO]: Queueing library & version downloads
[18:02:14 INFO]: Download job 'Version & Libraries' started (16 threads, 33 files)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.6.1\realms-1.6.1.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.15.Final\netty-all-4.0.15.Final.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar for job 'Version & Libraries'... (try 0)
[18:02:14 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Download job 'Resources' skipped as there are no files to download
[18:02:15 INFO]: Job 'Resources' finished successfully (took 0:00:00.000)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch-platform\6.5\twitch-platform-6.5-natives-windows-64.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch-platform\6.5\twitch-platform-6.5-natives-windows-64.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.1\lwjgl-platform-2.9.1-natives-windows.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.1\lwjgl-platform-2.9.1-natives-windows.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Attempting to download C:\Users\Robin\AppData\Roaming\.minecraft\versions\1.8 WDL\1.8 WDL.jar for job 'Version & Libraries'... (try 0)
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.15.Final\netty-all-4.0.15.Final.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.6.1\realms-1.6.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar for job 'Version & Libraries': Local file matches local checksum, using that
[18:02:15 INFO]: Finished downloading C:\Users\Robin\AppData\Roaming\.minecraft\versions\1.8 WDL\1.8 WDL.jar for job 'Version & Libraries': Couldn't connect to server (responded with 505) but have local file, assuming it's good
[18:02:15 INFO]: Job 'Version & Libraries' finished successfully (took 0:00:01.174)
[18:02:15 INFO]: Launching game
[18:02:15 INFO]: Unpacking natives to C:\Users\Robin\AppData\Roaming\.minecraft\versions\1.8 WDL\1.8 WDL-natives-29520661854511
[18:02:15 INFO]: Launching in C:\Users\Robin\AppData\Roaming\.minecraft
[18:02:15 INFO]: Half command: C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25\bin\javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Djava.library.path=C:\Users\Robin\AppData\Roaming\.minecraft\versions\1.8 WDL\1.8 WDL-natives-29520661854511 -cp C:\Users\Robin\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.15.Final\netty-all-4.0.15.Final.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.6.1\realms-1.6.1.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar;C:\Users\Robin\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar;C:\Users\Robin\AppData\Roaming\.minecraft\versions\1.8 WDL\1.8 WDL.jar net.minecraft.client.main.Main
[18:02:15 INFO]: Looking for orphaned versions to clean up...
[18:02:16 ERROR]: Game ended with bad state (exit code 1)
[18:02:16 INFO]: Ignoring visibility rule and showing launcher due to a game crash
[18:02:16 INFO]: Looking for old natives & assets to clean up...
[18:02:16 INFO]: Deleting C:\Users\Robin\AppData\Roaming\.minecraft\versions\1.8 WDL\1.8 WDL-natives-29520661854511

```

**Comment by Pokechu22** [comment]
Did you delete the `META-INF` folder?  If not, you should have.

**Comment by L3ice** [comment]
Its very strange.
I dont have folders in the 1.8.java file
There are no folders.
But when I use the unmodified 1.8 it works and there are no folders in it.

**Comment by Pokechu22** [comment]
Can you screenshot the contents of your jar?

**Comment by Pokechu22** [comment]
Actually... if you can't see the folder, you probably have your order set up weirdly.  I'm not sure what tool you're using to open the jar, but for most it'll just be clicking the text "Name" at the top.

> ![7-zip](https://cloud.githubusercontent.com/assets/8334194/8062971/7eae3224-0e87-11e5-8cc0-87e45ff52bf3.png)
> *In [7-zip](http://www.7-zip.org/)*
&nbsp;
> ![Windows explorer](https://cloud.githubusercontent.com/assets/8334194/8062972/80dc8708-0e87-11e5-8f8c-2ebd7ced2dd7.png)
> In windows explorer

Alternatively, when in the jar, just typing <kbd>META-INF</kbd> should bring you down to the folder regardless of its position.

I don't know how you managed to get the folders to not be at the top.

Tell me if that worked.

**Comment by L3ice** [comment]
Ok I will switch to 7Zip from Winrar because it does show folders in another way(Pretty stupid way).
Also the Testversion Screen annoys me.
So this was my fault.
I deleted the META-INF now and it works!
Thanks asap.
