### ISSUE TITLE
Minecraft crashes when I connect to hivemc server

### ISSUE THREAD

**Issue by ghost** [Pokechu22/WorldDownloader#63]
WorldDownloader cause Minecraft to crash when I connect to hivemc.com. It was working on previous version. Other servers working fine with WorldDownloader enabled

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 6/20/17 3:05 PM
Description: WDL mod: exception in onNHPCHandleCustomPayload event

java.lang.IndexOutOfBoundsException: readerIndex(37) + length(256) exceeds writerIndex(256): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf(ridx: 37, widx: 256, cap: 256/266)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1383)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:850)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:858)
	at gy.readBytes(SourceFile:930)
	at wdl.WDLHooks.onNHPCHandleCustomPayload(WDLHooks.java:296)
	at brx.handler$onHandleCustomPayload$zzc000(SourceFile:1875)
	at brx.a(SourceFile:1592)
	at iw.a(SourceFile:55)
	at iw.a(SourceFile:9)
	at hv$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at h.a(SourceFile:46)
	at bhz.az(SourceFile:991)
	at bhz.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 259173376 bytes (247 MB) / 471814144 bytes (449 MB) up to 4281597952 bytes (4083 MB)
	LiteLoader Brand: 1.12-SNAPSHOT-r1F07073-b2-2
	LiteLoader Mods: 2 loaded mod(s)
          - LiteModWDL version 4.0.0.4-1.12
          - VoxelMap version 1.6.22
	LaunchWrapper: 10 active transformer(s)
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
```

**Comment by Pokechu22** [comment]
Ah, yep, was afraid this would happen - there was a change to Netty, which made it much harder to directly get a byte array from the packetbuffer it gives you.  It'll be fixable, just got to figure out what the correct way to get a byte array from it is.

**Comment by Pokechu22** [comment]
This will be fixed in the next version.
