### ISSUE TITLE
Crashing on server connect?

### ISSUE THREAD

**Issue by 2tbc1887** [Pokechu22/WorldDownloader#82]
I don't know why this is happening
I installed using MultiMC instructions

Log here:
[16:12:17] [Client thread/INFO]: LWJGL Version: 2.9.4
[16:12:19] [Client thread/INFO]: Reloading ResourceManager: Default
[16:12:20] [Sound Library Loader/INFO]: Starting up SoundSystem...
[16:12:20] [Thread-3/INFO]: Initializing LWJGL OpenAL
[16:12:20] [Thread-3/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:12:20] [Thread-3/INFO]: OpenAL initialized.
[16:12:20] [Sound Library Loader/INFO]: Sound engine started
[16:12:27] [Client thread/INFO]: Created: 1024x512 textures-atlas
[16:12:29] [Client thread/INFO]: Narrator library for x64 successfully loaded
[16:12:51] [Client thread/FATAL]: World Downloader: Failed to add crash info
java.lang.NoClassDefFoundError: eq
	at b.h(CrashReport.java:108) [minecraft.jar:?]
	at b.<init>(CrashReport.java:40) [minecraft.jar:?]
	at b.a(CrashReport.java:341) [minecraft.jar:?]
	at bib.t(SourceFile:1627) [minecraft.jar:?]
	at bib.az(SourceFile:1000) [minecraft.jar:?]
	at bib.a(SourceFile:419) [minecraft.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: eq
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	... 15 more
[16:12:52] [Client thread/FATAL]: Reported exception thrown!
f: Updating screen events
	at bib.t(SourceFile:1635) ~[minecraft.jar:?]
	at bib.az(SourceFile:1000) ~[minecraft.jar:?]
	at bib.a(SourceFile:419) [minecraft.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_171]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_171]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_171]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_171]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_171]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_171]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_171]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at bwx.<init>(SourceFile:64) ~[minecraft.jar:?]
	at bwx.<clinit>(SourceFile:39) ~[minecraft.jar:?]
	at bib.a(SourceFile:2265) ~[minecraft.jar:?]
	at bib.a(SourceFile:2218) ~[minecraft.jar:?]
	at bkr.<init>(SourceFile:35) ~[minecraft.jar:?]
	at bnf.a(SourceFile:316) ~[minecraft.jar:?]
	at bnf.f(SourceFile:311) ~[minecraft.jar:?]
	at bnh.a(SourceFile:39) ~[minecraft.jar:?]
	at bjm.a(SourceFile:41) ~[minecraft.jar:?]
	at bnf.a(SourceFile:347) ~[minecraft.jar:?]
	at blk.k(SourceFile:400) ~[minecraft.jar:?]
	at bnf.k(SourceFile:86) ~[minecraft.jar:?]
	at blk.q(SourceFile:377) ~[minecraft.jar:?]
	at bib.t(SourceFile:1625) ~[minecraft.jar:?]
	... 11 more
---- Minecraft Crash Report ----
// Oops.

Time: 5/18/18 4:12 PM
Description: Updating screen events

java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at bwx.<init>(SourceFile:64)
	at bwx.<clinit>(SourceFile:39)
	at bib.a(SourceFile:2265)
	at bib.a(SourceFile:2218)
	at bkr.<init>(SourceFile:35)
	at bnf.a(SourceFile:316)
	at bnf.f(SourceFile:311)
	at bnh.a(SourceFile:39)
	at bjm.a(SourceFile:41)
	at bnf.a(SourceFile:347)
	at blk.k(SourceFile:400)
	at bnf.k(SourceFile:86)
	at blk.q(SourceFile:377)
	at bib.t(SourceFile:1625)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at bwx.<init>(SourceFile:64)
	at bwx.<clinit>(SourceFile:39)
	at bib.a(SourceFile:2265)
	at bib.a(SourceFile:2218)
	at bkr.<init>(SourceFile:35)
	at bnf.a(SourceFile:316)
	at bnf.f(SourceFile:311)
	at bnh.a(SourceFile:39)
	at bjm.a(SourceFile:41)
	at bnf.a(SourceFile:347)
	at blk.k(SourceFile:400)
	at bnf.k(SourceFile:86)
	at blk.q(SourceFile:377)

-- Affected screen --
Details:
	Screen name: bnf
Stacktrace:
	at bib.t(SourceFile:1625)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by 2tbc1887** [comment]
NEVERMIND GOT THE WRONG VERSION

**Comment by Pokechu22** [comment]
That was going to be my guess, that you installed one version of the mod targeting another Minecraft version.

There's _supposed_ to be some extra checks in place that give a clearer warning when versions are mixed, but I haven't tested them a lot; looks like it didn't work too well unfortunately.
